# Generated by Django 2.2.2 on 2021-05-23 01:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortCd', models.IntegerField(verbose_name='順番')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='表示色')),
            ],
        ),
    ]
