# Generated by Django 2.2.2 on 2021-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageType', '0002_auto_20210523_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=10, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='type',
            name='sortCd',
            field=models.IntegerField(unique=True, verbose_name='順番'),
        ),
    ]
