# Generated by Django 2.2.2 on 2021-02-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cls', models.IntegerField(choices=[(1, '周知'), (2, '検討'), (3, '作業')], default=1, verbose_name='種別')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('created_at', models.DateField(verbose_name='期限')),
                ('status', models.IntegerField(choices=[(1, '未着手'), (2, '着手中'), (3, '完了')], default=1, verbose_name='ステータス')),
            ],
            options={
                'verbose_name_plural': 'Header',
            },
        ),
    ]
