# Generated by Django 2.2.2 on 2021-02-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='created_at',
            new_name='limit_date',
        ),
    ]
