# Generated by Django 2.2.2 on 2021-05-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_auto_20210204_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='type_cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageType.Type'),
        ),
    ]
