# Generated by Django 2.2.2 on 2021-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_auto_20210523_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='limit_date',
            field=models.DateField(blank=True, verbose_name='期限'),
        ),
    ]
