# Generated by Django 2.2.2 on 2021-06-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_auto_20210529_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='type_cls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageType.Type'),
        ),
    ]
